### ISSUE TITLE
Fix a few issues

### ISSUE THREAD

**Issue by Tonkpils** [AppDojo/AppDojo.github.io#9]
A few things for the Contact Us
- [x] Contact Us button at the bottom of the index page is not linked to the contact page
- [ ] Tabs on the Contact Us page change the URL but nothing happens
- [ ] List of people in the Contact Us Page should be App Dojo Organizers and link to their emails
- [ ] Load Gravatar images for those who have them.

Anything else we can think of?

**Comment by Destiny10** [comment]
linked the contact us button to the page :-)

**Comment by Destiny10** [comment]
" Load Gravatar images for those who have them." Are you talking about the contact us page or the App Dojo members?

**Comment by Tonkpils** [comment]
That one might be a bit more involved. So, for each member in the members page, we should include the Gravatar link instead of the placeholder image.

**Comment by Tonkpils** [comment]
@Destiny10 Also, if you have any suggestions don't hesitate to make a new issue to talk about it or create a pull request so we can go over it. :dancer:

**Comment by Destiny10** [comment]
" List of people in the Contact Us Page should be App Dojo Organizers and link to their emails" who are the organizers etc?

**Comment by Destiny10** [comment]
i was looking at the contact us page and im not sure if its a typo "  We love getting email all day all day " Do you mean "  We love getting emails all day everyday".?

**Comment by Tonkpils** [comment]
I guess so, I didn't write the Contact Us page. We are working on the AppDojo API to be able to get a list of organizers and stuff so we can dynamically load that. In the end I think this will be the front end to the AppDojo webapp as well so we'll probably have to modify a few things. For now this is a work in progress.
